language: swift
osx_image: xcode9.1
branches:
  only:
    - master
    - develop
env:
  global:
  - PROJECT_NAME="Spinner.xcodeproj"
  - IOS_FRAMEWORK_SCHEME="Spinner"
  - TVOS_FRAMEWORK_SCHEME="Spinner-tvOS"

  - IOS_SDK=iphonesimulator11.1
  - TVOS_SDK=appletvsimulator11.0

  matrix:
  - DESTINATION="OS=11.1,name=iPhone 6S Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
  - DESTINATION="OS=11.0,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"

script:
  - set -o pipefail

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT_NAME" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test | xcpretty;
    else
      xcodebuild -project "$PROJECT_NAME" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build in release
  - xcodebuild -project "$PROJECT_NAME" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;

after_success:
- bash <(curl -s https://codecov.io/bash)
